language: java
jdk: oraclejdk11
before_script:
  - echo "Starting build"
script:
  - mvn clean package
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful.
after_failure:
  - echo "Build was failed"